// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"time"
)

type Flat struct {
	ID           string
	ExternalID   string
	Name         string
	Address      string
	City         string
	Price        int64
	ZipCode      string
	Size         string
	Availability string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
