CREATE TABLE flats (
    id VARCHAR(255) NOT NULL,
    external_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    size VARCHAR(255) NOT NULL,
    availability VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);